services:
  postgres_database:
    image: postgres:16
    container_name: postgres_database
    environment:
      POSTGRES_DB: relatos_database
      POSTGRES_USER: relatos
      POSTGRES_PASSWORD: relatos
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relatos -d relatos_database"]
      interval: 10s
      timeout: 5s
      retries: 10
